"""Initial schema with explicit FTS5 search index

Revision ID: 0001
Revises:
Create Date: 2026-09-16

The FTS5 virtual table and its sync triggers are written by hand rather than
autogenerated: Alembic cannot render a virtual table, and the external-content
configuration below is what keeps the index in step with ``findings`` without
duplicating the evidence text (PRD 7.5, R20).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Columns mirrored into the search index, in index order.
FTS_COLUMNS = (
    "title",
    "summary",
    "kind",
    "module",
    "host",
    "normalized_value",
    "raw_evidence",
)


def _column_list(prefix: str = "") -> str:
    return ", ".join(f"{prefix}{column}" for column in FTS_COLUMNS)


def upgrade() -> None:
    op.create_table(
        "scope_profiles",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("name", sa.String(length=120), nullable=False, unique=True),
        sa.Column("entries_json", sa.JSON(), nullable=False),
        sa.Column("allow_cgnat", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("allow_link_local", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "scans",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("target_input", sa.String(length=255), nullable=False),
        sa.Column("target_normalized", sa.String(length=255), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("resolved_addrs_json", sa.JSON(), nullable=False),
        sa.Column("intensity_profile", sa.String(length=32), nullable=False),
        sa.Column("selected_modules_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("attestation_text", sa.Text(), nullable=False),
        sa.Column("attestation_version", sa.String(length=32), nullable=False),
        sa.Column("attestation_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("claimed_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["scope_id"], ["scope_profiles.id"], ondelete="RESTRICT", name="fk_scans_scope"
        ),
    )
    op.create_index("ix_scans_status", "scans", ["status"])
    op.create_index("ix_scans_created_at", "scans", ["created_at"])

    op.create_table(
        "module_runs",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("scan_id", sa.String(length=36), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cache_hit", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("finding_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("safe_error_code", sa.String(length=64), nullable=True),
        sa.Column("safe_error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], ondelete="CASCADE", name="fk_module_runs_scan"
        ),
        sa.UniqueConstraint("scan_id", "module", name="uq_module_run_scan_module"),
    )
    op.create_index("ix_module_runs_scan_id", "module_runs", ["scan_id"])

    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("scan_id", sa.String(length=36), nullable=False),
        sa.Column("host", sa.String(length=64), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.JSON(), nullable=False),
        sa.Column("raw_evidence", sa.Text(), nullable=True),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=True),
        sa.Column("sources_json", sa.JSON(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], ondelete="CASCADE", name="fk_findings_scan"
        ),
    )
    op.create_index("ix_findings_scan_id", "findings", ["scan_id"])
    op.create_index("ix_findings_scan_category", "findings", ["scan_id", "category"])
    op.create_index("ix_findings_scan_module", "findings", ["scan_id", "module"])
    op.create_index("ix_findings_scan_host_port", "findings", ["scan_id", "host", "port"])
    op.create_index("ix_findings_fingerprint", "findings", ["fingerprint"])

    op.create_table(
        "scan_ledger",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("scan_id", sa.String(length=36), nullable=True),
        sa.Column("destination", sa.String(length=64), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], ondelete="CASCADE", name="fk_ledger_scan"
        ),
        sa.CheckConstraint("decision in ('allowed', 'denied')", name="ck_ledger_decision"),
    )
    op.create_index("ix_scan_ledger_scan_id", "scan_ledger", ["scan_id"])
    op.create_index("ix_ledger_scan_decision", "scan_ledger", ["scan_id", "decision"])

    op.create_table(
        "scan_events",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("scan_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], ondelete="CASCADE", name="fk_events_scan"
        ),
        sa.UniqueConstraint("scan_id", "sequence", name="uq_event_scan_sequence"),
    )
    op.create_index("ix_scan_events_scan_id", "scan_events", ["scan_id"])

    op.create_table(
        "cache_entries",
        sa.Column("cache_key", sa.String(length=255), primary_key=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column("normalized_json", sa.JSON(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_cache_entries_expires_at", "cache_entries", ["expires_at"])

    op.create_table(
        "worker_lock",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("hostname", sa.String(length=120), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
    )

    _create_fts5()


def _create_fts5() -> None:
    """External-content FTS5 index over findings, kept in sync by triggers."""
    op.execute(
        f"""
        CREATE VIRTUAL TABLE findings_fts USING fts5(
            {_column_list()},
            content='findings',
            content_rowid='rowid',
            tokenize='unicode61'
        )
        """
    )

    op.execute(
        f"""
        CREATE TRIGGER findings_fts_ai AFTER INSERT ON findings BEGIN
            INSERT INTO findings_fts(rowid, {_column_list()})
            VALUES (new.rowid, {_column_list("new.")});
        END
        """
    )

    # 'delete' rows carry the OLD values: FTS5 external content needs them to
    # remove the right index entries.
    op.execute(
        f"""
        CREATE TRIGGER findings_fts_ad AFTER DELETE ON findings BEGIN
            INSERT INTO findings_fts(findings_fts, rowid, {_column_list()})
            VALUES ('delete', old.rowid, {_column_list("old.")});
        END
        """
    )

    op.execute(
        f"""
        CREATE TRIGGER findings_fts_au AFTER UPDATE ON findings BEGIN
            INSERT INTO findings_fts(findings_fts, rowid, {_column_list()})
            VALUES ('delete', old.rowid, {_column_list("old.")});
            INSERT INTO findings_fts(rowid, {_column_list()})
            VALUES (new.rowid, {_column_list("new.")});
        END
        """
    )


def downgrade() -> None:
    for trigger in ("findings_fts_au", "findings_fts_ad", "findings_fts_ai"):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    op.execute("DROP TABLE IF EXISTS findings_fts")

    op.drop_table("worker_lock")
    op.drop_table("cache_entries")
    op.drop_table("scan_events")
    op.drop_table("scan_ledger")
    op.drop_table("findings")
    op.drop_table("module_runs")
    op.drop_table("scans")
    op.drop_table("scope_profiles")
